services:

  cards_app:
    tty: true
    build:
      context: .
      args:
        requirements: requirements/reqs.txt
    container_name: cards_app
    environment:
      # use in code
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - .:/app:delegated
    ports:
      - 8001:8001
    depends_on:
      - postgres 
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload

  postgres:
    image: postgres:14
    container_name: cards_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cards_db
    ports:
      - 5432:5432
